### ISSUE TITLE
Bugs with the new Copy/Move menu in contacts

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#101]
When the contextmenu is enabled The more actions menu has some issues.

1. Elastic skin: Broken icon on addressbook in addressbook selector
2. Elastic skin: JS error when clicking content frame with addressbook selector menu opened (not contextmenu).
3. Larry skin: Main menu disappears when clicking Copy to... in the menu (not contextmenu).
4. The menu is broken (does not disappear) after addressbook selector use.

I didn't tested with classic skin.

**Comment by johndoh** [comment]
confirmed. Contextmenu implemented its own version of the move/copy widgets in address book, now the PR has been merged they are not needed any more 920562e should make Contextmenu compatible again.
