### ISSUE TITLE
Click on QR Code entry in the menu does not hide the menu

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#102]
1. Goto Contacts
2. Right-click on a contact record to display the context menu
3. Click on More...
4. Click on Assign to group... (need to be enabled)
5. Click on QR Code.

Result: QR code dialog appears but all three menus stay on the screen.

**Comment by johndoh** [comment]
I think this is really solved now. Thanks for merging that PR, while I was testing I found some other issues which lead me to a better solution so it turns out the PR wasn't needed in the end. Sorry for the noise.
