### ISSUE TITLE
Add contextmenu in Settings

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#103]
Settings > Folders
Settings > Identities
Settings > Responses
also
Settings > Filters (managesieve)
Settings > PGP Keys (enigma)

**Comment by johndoh** [comment]
I've started working on this in [settings-menus branch](https://github.com/johndoh/roundcube-contextmenu/tree/settings-menus).

there are a few issues:
* a small tweak is needed in the `maangesieve` plugin to allow `contextmenu` to execute the `delete` action. there are a few other places in the core than need similar tweaks to multi-step commands. I have submitted a [PR](https://github.com/roundcube/roundcubemail/pull/6145) for this.
* new events needed in list/treelist widgets:
  * tigger the `getselection` event also when doing `get_single_selection`. In mail/addressbook task there are speical functions `get_single_uid`/`get_single_cid` but in the `settings` task there is nothing like that so triggering the generic `getselection` event allows `contextmenu` to provide the correct selection for the action.
  * `enigma` plugin creates its own list object which `contextmenu` needs to interact with (to know when a new key is added) so I propose a new `init_list` global event to annouce when a list object is created.
  * an even is needed the treelist widget similar to the `initrow` event in the list widget so `contextmenu` can detect when a new folder is added to the list.
  * I have submitted a [PR](https://github.com/roundcube/roundcubemail/pull/6180) for this.
* there is a problem with the `responses` template in the `classic` and `larry` skins, it thinks its `identities`. I have submitted a [PR](https://github.com/roundcube/roundcubemail/pull/6185) for this.
* filter list refreshes when opening contextmenu on filder set list in managesieve plugin.

Not a problem but may be worth improving I noticed that the settings list (preferences/folders/identities etc) is rather inconsistent. some elements have `onclick` some have `href` and some have both. This is not limited to core vs plugin entries. For example `preferences` has `href` and `onclick` while `responses` has only `onclick`.

**Comment by johndoh** [comment]
settings-menu branch merged into master

**Comment by johndoh** [comment]
any suggestions how to solve the list refresh when opening contextmenu on filter set list in managesieve plugin welcome.

**Comment by alecpl** [comment]
I investigated filters list issue and see part of the problem.Generally contextmenu calls 'select' event on the list object with fake (unset) rcmail.env.contentframe. This works with filters list, but will not work with filter sets list because of how the select handler looks like. See managesieve_setselect().

So, `this.filters_list.clear(true);` would need to be moved inside the `if` statement, but still we'll need some global flag that could be read there to skip list reload when the select handler is invoked by contextmenu action. I don't know contextmenu plugin code well, so I'm open for suggestions.

**Comment by johndoh** [comment]
I've fixed the purge/empty command problem.

For the filter set list. I wasn't just if adjusting the existing managesieve code was an option but if it is then adding a check like this in after the commands are enabled/disabled should do the trick:
```js
if (rcmail.env.contextmenu_opening)
  return;
```
`rcmail.env.contextmenu_opening` can be set to a couple of different things while the menu is opening but the rest of the time its null. It is contextmenu specific rather than global though so I'm not sure.

eg:
```diff
--- a/plugins/managesieve/managesieve.js
+++ b/plugins/managesieve/managesieve.js
@@ -157,13 +157,17 @@
 // Set selection
 rcube_webmail.prototype.managesieve_setselect = function(list)
 {
-  this.show_contentframe(false);
-  this.filters_list.clear(true);
   this.enable_command('plugin.managesieve-setdel', list.rowcount > 1 && $.inArray('delete_set', rcmail.env.managesieve_disabled_actions) == -1);
   this.enable_command('plugin.managesieve-setact', list.rowcount > 0 && $.inArray('enable_disable_set', rcmail.env.managesieve_disabled_actions) == -1);
   this.enable_command('plugin.managesieve-setget', list.rowcount > 0 && $.inArray('delete_set', rcmail.env.managesieve_disabled_actions) == -1);
   this.enable_command('plugin.managesieve-seteditraw', list.rowcount > 0 && this.env.raw_sieve_editor);

+  if (rcmail.env.contextmenu_opening)
+    return;
+
+  this.show_contentframe(false);
+  this.filters_list.clear(true);
+
   var id = list.get_single_selection();
   if (id != null) {
     this.managesieve_list(this.env.filtersets[id]);
```

**Comment by alecpl** [comment]
I applied the patch. There's one more issue. Steps:
1. Goto Filters
2. Right-click a filter-set record that is not the selected one, use Open.
3. Right-click a record on filters list. It does not work with an error in console: "TypeError: list.rows[id] is undefined in managesieve.js:148:5"

As I see the id variable in managesieve_select() is the one of the selected filter-set not the right-clicked filter record.

**Comment by johndoh** [comment]
all the issues here are solved so I'm closing this.
