### ISSUE TITLE
"Save search" in addressbooks menu

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#108]
The "Save search" option is missing. I think it would be good to add it for consistency with the options menu.

**Comment by johndoh** [comment]
I'm not sure where such an option would go. "Save search" is not an action you can perform on an addressbook, a group, or an individual contact.

**Comment by alecpl** [comment]
Yeah. When I saw "Delete search" my first thought was "where is Save search item?", but maybe that's only me. Let's ignore my request for now. You're right.
