### ISSUE TITLE
Context-menu frontend error

### ISSUE THREAD

**Issue by kveriz** [johndoh/roundcube-contextmenu#111]
When I try change page of list emails with contexmenu which contains number of pages I get the error 
```
contextmenu.js?s=1429340030:1002 Uncaught TypeError: Cannot read property 'currentTarget' of undefined
    at contextmenu.js?s=1429340030:1002
    at rcube_webmail.triggerEvent (common.js?s=1550051890:373)
    at rcube_webmail.hide_menu (app.js?s=1550051890:8097)
    at HTMLInputElement.<anonymous> (app.js?s=1550051890:3492)
    at HTMLInputElement.dispatch (jquery.min.js?s=1550051933:37)
    at HTMLInputElement.r.handle (jquery.min.js?s=1550051933:37)
    at Object.trigger (jquery.min.js?s=1550051933:37)
    at HTMLInputElement.<anonymous> (jquery.min.js?s=1550051933:37)
    at Function.each (jquery.min.js?s=1550051933:36)
    at o.fn.init.each (jquery.min.js?s=1550051933:36)
```
I'm using plugin version 2.3 and roundcube 1.3.5 with Larry theme. The same behavior is on the other themes too. I don't use extensions which affect JS. Browser is Chrome 72.0.3626.9, but the I saw the issue on older versions.

![peek 2019-02-22 04-03](https://user-images.githubusercontent.com/44600933/53212987-370afe00-3658-11e9-8e00-913d52688eb1.gif)

If you need more information about this issue I'm ready to provide it.

**Comment by johndoh** [comment]
are you sure you are running version 2.3 of the contextmenu plugin? I think this issue was fixed by https://github.com/johndoh/roundcube-contextmenu/commit/1d2fcad543aeaf9f4747233ae5d51ebf3c160ed8 which is in both 2.3 and 2.2.

In version 2.3 [line 1002](https://github.com/johndoh/roundcube-contextmenu/blob/2.3/contextmenu.js#L1002) is a return statement.

**Comment by kveriz** [comment]
I think yes - composer.json file contains version 2.3.

**Comment by johndoh** [comment]
please could you at least compare your JS file with the one in the repo? may be there was a problem when you were installing an update one time or something.

**Comment by kveriz** [comment]
Yes. It seems you are right. I've compared files and checksum is different
 
From git repo
```
$ cksum contextmenu.js
1632010729 52003 contextmenu.js
```
Using file
```
# cksum ./plugins/contextmenu/contextmenu.js
3840343999 33469 ./plugins/contextmenu/contextmenu.js
```

So. I'll try updating roundcube correctly and check work of plugin. But I didn't see any errors when I did it earlier. Thank you so much anyway.

**Comment by johndoh** [comment]
no feedback
