### ISSUE TITLE
Visual issue with a selected message

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#113]
Steps:
1. Goto Mail.
2. Select three messages on the list (with Ctrl + click).
3. Right-click one of them.
4. In the contextmenu click More, then click Move to...
![contextmenu-issue](https://user-images.githubusercontent.com/546788/56283716-d1e0ff80-6112-11e9-81ab-c2f9c2e7898d.png)
Note, that the colors will not change when invoking the contextmenu, nor when click More. You have to goto deeper levels of the menu.

**Comment by alecpl** [comment]
Not a problem in classic and elastic skins.

**Comment by johndoh** [comment]
fixed
