### ISSUE TITLE
Elastic: Menu sometimes does not disappear

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#114]
This is a rare case, but... To reproduce you have to have at least two addressbooks (e.g. ldap and sql). Steps:
1. In Elastic (no issue in Larry) go to Contacts
2. Right-click on contacts list
3. Click "More..."
4. Click "Copy to..."
5. Click "QR Code"

Result: The first level contextmenu stays on top of the QR Code dialog.
Expected: All menus disappear.

Note: It does not happen if I skip step 4.

**Comment by johndoh** [comment]
I think this has to do with the popover code in Elastic that replaces the normal popup menu handling in the core. In some cases when a BS popover is closed a `menu-close` JS event is not triggered. I'm still investigating.

**Comment by johndoh** [comment]
I've added a hack to fix the specific case mentioned above. I'd prefer to solve the root cause but I cannot track it down. The biggest difference I can find between Larry and Elastic is that Elastic does not trigger `menu-close` events. Any help appreciated.

**Comment by johndoh** [comment]
I think this is sorted in 5a2a748
