### ISSUE TITLE
Use browser.menus API

### ISSUE THREAD

**Issue by rshadow** [johndoh/roundcube-contextmenu#117]
In the latest version of Firefox 68, I do not have a context menu. I think this is due to the transition to the browser api.
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus

**Comment by johndoh** [comment]
Works for me in FF68. I think your link refers to adding elements to the browser's context menu, I think for firefox addons. That is not what this plugin does.

What version of Roundcube are you running and what version of this plugin? Also what skin. Have you tried with all other plugins disabled? Check the browser console for JS errors.

**Comment by rshadow** [comment]
I found what the problem was.
I used the plugin from the Debian distribution. When I used the plugin form githab, it all worked.
