### ISSUE TITLE
Emptying a folder with unread messages via context menu doesn't remove unread message badge

### ISSUE THREAD

**Issue by smares** [johndoh/roundcube-contextmenu#120]
The folder list displays a badge with the count of unread messages (if any). When using the contextmenu plugin to empty a folder (e.g. Trash), the operation succeeds, but the unread count is not reset / removed. Not sure if Roundcube offers an appropriate hook which the plugin could use. If not, maybe this can be addressed.

**Comment by smares** [comment]
Related to https://github.com/johndoh/roundcube-contextmenu/issues/76#issuecomment-208429113

**Comment by johndoh** [comment]
the change is in roundcube git-master. I think it will be included in the 1.4.2 release

**Comment by smares** [comment]
Thanks! Any info about the other problem I mentioned in #76 ?

**Comment by johndoh** [comment]
I cannot recreate it
