### ISSUE TITLE
Option to empty a folder containing messages (e.g. Trash) is sometimes greyed out

### ISSUE THREAD

**Issue by smares** [johndoh/roundcube-contextmenu#121]
This issue is related to #76 and my comments https://github.com/johndoh/roundcube-contextmenu/issues/76#issuecomment-555158004 and https://github.com/johndoh/roundcube-contextmenu/issues/120#issuecomment-555156100

I can always reproduce this issue like this (using Roundcube 1.4.1 and contextmenu 3):

1. Log in to Roundcube, load the Trash folder, and empty it if it contains any messages, then switch to Inbox and log out.
2. Using an IMAP client which is not Roundcube (e.g. mail app on your phone, mail client on your desktop), delete a message so that it's moved to the Trash folder.
3. Log in to Roundcube and right-click the Trash folder while still being in Inbox and without loading the Trash folder first. --> The Empty option is greyed out.
4. Open the Trash folder. --> The folder is refreshed from the IMAP server and the message from step 2 shows up. If you right-click Trash now, the Empty option is enabled.

I assume this has to do with the fact that when you logged out in step 1, Roundcube cached that the folder is empty. Since the action performed in step 2 was outside of Roundcube, when you logged in in step 3 and right clicked on Trash, Roundcube still assumed the folder was empty resulting in the option being greyed out.

**Comment by smares** [comment]
Maybe it's worth mentioning that memcache is being used as IMAP cache!

**Comment by johndoh** [comment]
I think it has to do with the message caching. When you log back in to Roundcube does the trash icon change from empty to full? Do you have Rounducbe set to check all folders for new messages? I think at login Roundcube checks for unread messages not message existence. If Rounducbe does not know there are any messages in the folder the option will be greyed out.

It is possible to force a check to get the latest information from the IMAP server but IMO its not approirate to do that every time the context menu is opened and it could also cause the context menu to be out of sync with the rest of the UI.
