### ISSUE TITLE
Version check failed

### ISSUE THREAD

**Issue by Hariko50** [johndoh/roundcube-contextmenu#123]
[Exception]                                                                                               
Version check failed! johndoh/contextmenu requires Roundcube version >= 1.4.999.0, 1.4.2.0 was detected.

**Comment by johndoh** [comment]
The git-mast branch of this plugin requires the git-master branch of Roundcube. You should use the release-3.0 branch.

**Comment by Hariko50** [comment]
Unfortunately, I don't understand what you mean by that.
I install the plugin with php composer.phar update.
Where do I have to change which settings?

**Comment by johndoh** [comment]
In your `composer.json` file. I think you want the line for the contextmenu plugin to say something like `"johndoh/contextmenu": "~3.0"`
