### ISSUE TITLE
Zipdownload menu items not active

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#125]
1. Goto messages list (with no selection) and right-click a message
2. In the contextmenu goto More... -> Download...

The result is a menu with three inactive options. The first one ("Source (.eml)") should be active.

I'd need a fix or a quick hint on how to fix that.

**Comment by johndoh** [comment]
I have submitted a PR to fix this. Its an issue with when the menu items are enabled/disabled for the contextmenu to have influence it needs to menu when the menu is opened not on list select change.

**Comment by alecpl** [comment]
Merged. Thank you.
