### ISSUE TITLE
how to turn backgrou menu from oscure almost black to white?

### ISSUE THREAD

**Issue by mckaygerhard** [johndoh/roundcube-contextmenu#129]
i am made a skin that is white based.. but context menu loads of course black.. there are only two places where a background color is defined and i changes but no luck.. 

of course i copy the larry directory of contextmenu and changed name.. to "newskin" and it loads.. but is black..

**Comment by johndoh** [comment]
that comes from the .popupmenu menu style in the code. see https://github.com/roundcube/roundcubemail/blob/master/skins/larry/styles.css#L2239 so you'd need to change that style in your "newskin" skin.
