### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by gianlucagiacometti** [johndoh/roundcube-contextmenu#130]
I would like to propose swapping "Empty" and "Mark all as read" in the menu. Usually, the most dangerous command should be the last one. I would also suggest a red colour for the word "Empty".
I came to this request after mistakenly emptying two or three folders a week after empty folders different than Junk and Bin was activated.
If you approve, should I create a PR?

**Comment by johndoh** [comment]
The order of the items in the menu comes from the core. In the folder menu I do add a few extra items at the top but most of it is read from the folder menu in the skin. Modifying the order would be quite a bit change I think and I have not hear of any rule about the most dangerous command being last in menus.

Its a similar case with the styling, I try to keep the styling as close to the rest of the skin as possible, so it all looks like it belongs together and certainly none of the core skins use multi coloured menus.

For me it does not make sense to change one menu and not the other, the user could be confused as to why they are different so perhaps a better approach would be for you to create a custom skin you could change the order of the menu items and the styling and then that will be picked up by this plugin.

> I came to this request after mistakenly emptying two or three folders a week after empty folders different than Junk and Bin was activated.

Another possible solution might be to modify the confirmation message that is displayed when you click Empty to include the name of the target folder. This is something in the core, beyond the control of this plugin.

**Comment by gianlucagiacometti** [comment]
Thank you very much for your kind and detailed explanation. Indeed there is no official rule about last command within a menu, but "exit" is usually the last one, and in some cases, very reasonably in my opinion, also "delete". I will investigate the core further and move the request to roundcubemail repository.
