### ISSUE TITLE
First have to left click

### ISSUE THREAD

**Issue by remkohat** [johndoh/roundcube-contextmenu#135]
Installed roundcube 1.4.3 (elastic skin) and plugins from Ubuntu 20's repo.
Manually upgraded contextmenu to 3.3.1 because repo contains 2.3 which has no elastic skin.

When right clicking on a folder that wasn't first left clicked makes a servererror appear at the bottom right of the window.
The contextmenu appears but whatever you click doesn't do a thing.
Same for emails that weren't first left clicked but without the error.

Only if you first left click a folder or email before you right click it than the contextmenu works fine.

**Comment by ichirugame** [comment]
Is it an error if I download roundcube from https://roundcube.net/download/ instead of the repository?

**Comment by remkohat** [comment]
Manual upgrade to the latest 1.4.13 seems to give a little improvement.
I can now right click emails and do things from within the contextmenu to it without first having to left click the email.
But folders remain the same.

**Comment by ichirugame** [comment]
Are there any errors in the roundcube logs or server logs?

**Comment by ichirugame** [comment]
Are you calling an undefined method?
Please check the file that is giving the error once.

**Comment by johndoh** [comment]
This sounds like a version compatibility issue. You said you were running Roundcube 1.4.3 and Contextmenu 3.3.1 but v3.3.1 is for  Roundcube 1.5 and above.

Now you have Roundcube 1.4.13 you could use v3.2.1 of Contextmenu . See the [releases](https://github.com/johndoh/roundcube-contextmenu/releases) page for all versions.
