### ISSUE TITLE
404 errors trying to fetch plugin css/js (v3.3.1)

### ISSUE THREAD

**Issue by kangsterizer** [johndoh/roundcube-contextmenu#136]
Might be doing something wrong elsewhere, and I'm not sure how Roundcube registers these URLs, but I guess 404's in the browser console like these:

```
GET /plugins/contextmenu/contextmenu.js?s=1693830724 net::ERR_ABORTED 404 (Not Found)
GET /plugins/contextmenu/skins/elastic/functions.js?s=1693830724 net::ERR_ABORTED 404 (Not Found)
```

which cause the plugin to fail. This seems to work fine for my other plugins (and they do have a `/plugins/plugin-name-here/...` file which i can fetch just fine, including plugins that weren't bundled by Roundcube).

The plugin is also installed in the same path on disk - and no errors in `/var/log/roundcubemail/errors.log` or from PHP. I'm using plugin version 3.3.1 (latest release). I'm using the elastic theme.

Any idea?

**Comment by johndoh** [comment]
are you sure you put the files in the right place? this sounds like a webserver issue not a plugin one. sorry.
