### ISSUE TITLE
kolab_addressbook plugin support

### ISSUE THREAD

**Issue by alecpl** [johndoh/roundcube-contextmenu#94]
It used to work, so a regression. When the plugin is enabled contextmenu on addressbooks does not work.

It is because kolab_addressbook modifies the list structure. It changes `li > a` to 'li > div > a`, so `var source = $(this).children('a')` does not find any nodes. I added this:
```
if (!source.length) {
    source = $(this).children('div').find('a');
}
```
and menu appears, but it's actions are not activated properly, so there's some more changes needed. This is Kolab's code https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_addressbook/kolab_addressbook.js;1f0f28204900364d01ba2fd8b9b99e8d44a7b3cc$595 Any hints?

**Comment by johndoh** [comment]
I think 5a0e5c4 will help with the first part. I'm not sure about the second bit though. Is there any chance I could get a test login to your system so I can have a look at it? roundcube at tehinterweb dot co dot uk

**Comment by johndoh** [comment]
Thanks for the login. All the Kolab actions besides book-create are disabled because of this line https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_addressbook/kolab_addressbook.js;1f0f28204900364d01ba2fd8b9b99e8d44a7b3cc$602. I think may be you don't need the menu you build starting at line 577 and instead move the activate function from your new menu to line 564?

**Comment by alecpl** [comment]
I'm stupid. I completely ignored lines 587 to the end of file, where we overwrite default contextmenu. There was needed a fix for menu_source definition, but still it does not work. Looks like menu replacing is not working at all. Any hints now?

**Comment by johndoh** [comment]
does this help at all? https://gist.github.com/johndoh/b68b363ed1cfe0963aba210a9fd24256

**Comment by alecpl** [comment]
Thanks, this way it's working. Do you know if this will work with 2.3?

**Comment by johndoh** [comment]
The activate event code will but you also need 5a0e5c4

**Comment by alecpl** [comment]
Thank you.
